Update to 10.0.2 + minor improvements

diff --git a/AppRun b/AppRun
--- a/AppRun
+++ b/AppRun
@@ -9,14 +9,25 @@ HERE="$(readlink -f "$(dirname "$0")")"
 # Set up PATH environment variable to prefer executables from AppImage.
 export PATH="${HERE}/usr/bin:${PATH}"
 
-# Run a custom executable if specified. Otherwise launch the default.
+# Find the name of the program, and, if custom, verify its existence.
 if test ! -z "${APPIMAGE_EXE}"; then
   if test -x "${HERE}/usr/bin/${APPIMAGE_EXE}"; then
-    exec "${HERE}/usr/bin/${APPIMAGE_EXE}" "$@"
+    EXE="${HERE}/usr/bin/${APPIMAGE_EXE}"
+  elif test "${APPIMAGE_EXE}" = "list"; then
+    find "${HERE}/usr/bin" -type f -executable -exec basename {} ';'
+    exit 0
   else
-    echo "ERROR: ${APPIMAGE_EXE} not found in AppImage." >&2
+    echo "ERROR: Program '${APPIMAGE_EXE}' not found in AppImage." >&2
     exit 1
   fi
 else
-  exec "${HERE}/usr/bin/qemu-system-x86_64" "$@"
+  # No custom program was set, so default to 'qemu-system-x86_64'.
+  EXE="${HERE}/usr/bin/qemu-system-x86_64"
+fi
+
+# If it is a 'qemu-system' binary, run with -L to set runtime path.
+if basename "${EXE}" | grep -q "^qemu-system"; then
+  exec "${EXE}" -L "${HERE}/usr/share/qemu" "$@"
+else
+  exec "${EXE}" "$@"
 fi
